# Generated by Django 2.2.6 on 2020-02-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number_of_hours',
            new_name='number_of_minutes',
        ),
    ]
