# Generated by Django 2.2.6 on 2020-03-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogone', '0002_coursereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
