# Generated by Django 2.2.6 on 2020-03-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
