# Generated by Django 2.2.6 on 2020-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
