# Generated by Django 2.2.6 on 2020-02-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_course_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
