# Generated by Django 2.2.6 on 2020-02-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_course_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
