# Generated by Django 2.2.6 on 2020-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200226_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
