# Generated by Django 2.2.6 on 2020-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200226_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('number_of_minutes', models.IntegerField()),
                ('cost', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
