# Generated by Django 2.2.6 on 2020-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_course_pass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Pass',
            new_name='CoursePass',
        ),
    ]
