# Generated by Django 2.2.6 on 2020-02-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200227_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepass',
            name='number_of_minutes',
        ),
    ]
