# Generated by Django 2.2.6 on 2020-03-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_coursepass_number_of_minutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePass',
        ),
    ]
