# Generated by Django 2.2.6 on 2020-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number_of_hours',
            new_name='number_of_minutes',
        ),
        migrations.AddField(
            model_name='course',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
