# Generated by Django 2.2.6 on 2020-02-26 15:15

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_course_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('number_of_minutes', models.IntegerField()),
                ('image', pyuploadcare.dj.models.ImageField(null=True)),
                ('cost', models.FloatField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('quantity', models.FloatField(default=1)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Instructor')),
            ],
        ),
    ]
